site_name: 大模型应用开发：从 0 到 1
site_author: Seamile
repo_url: https://github.com/seamile/llm-0t1
theme:
  name: cinder
nav:
  - 引言: index.md
  - 初识大模型:
      - 01.初识大模型.md
      - 02.大模型是怎么工作的.md
  - LLM应用开发:
      - 02.提示工程.md
  - LangChain:
      - ...
  - LLM进阶:
      - ...
